admin/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from gsmApp.sitemap import *
sitemaps={
    'resource':resourcesitemap,
    'brand':brandsitemap,
    'model':modelsitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gsmApp.urls')),
    path('blog/', include('blogApp.urls')),
    path('subscription/',include('subscriptionApp.urls')),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    # path('paypal/', include('paypal.standard.ipn.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap')
  
]
# ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# summernotes
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subscriptionApp/urls.py
from django.urls import path
from.views import *

urlpatterns = [
    path('', subscriptions, name='subscription'),
    path('paymentProcess/<slug>/', payment_process, name='payment_process'),
    path('payment/<slug>/', payment, name="payment"),
    path('increment-file-count/<slug>/',incrementFileCount,name="increment-file-count"),
    path('file-payment/<int:id>/',single_file_Payment,name="single_file_payment"),
    path('singleFilePaymentProcess/<int:id>/', single_file_payment_process, name='single_file_payment_process'),
    path('upload-file/', upload_file, name="upload_file"),
    path('upload-brand/', upload_brand, name="upload_brand"),
    path('upload-blog-post/',upload_blog_post, name="upload_blog_post"),
    path('payment-process/',process_payment),
    path('payment-success',payment_success),
    path('payment-cancel',payment_success)
    
]

gsmApp/models.py

from distutils.archive_util import make_zipfile
from distutils.command.upload import upload
from email.policy import default
from django.db import models
import uuid
from django.utils import timezone
from django.utils.text import slugify
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.db.models.signals import post_save,pre_save,m2m_changed
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext as _
from subscriptionApp.models import *
from django.dispatch import receiver
from tagulous.models import TagField
from taggit.models import Tag


def slug_set(sender, instance, **kwargs):
     instance.slug = slugify(instance.title)

#category model     
class category(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField(default="", blank=True)

    def __str__(self):
     return self.title 
pre_save.connect(slug_set, sender=category)  

#brand model
class brand(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField(default="", blank=True, unique=True)

    def __str__(self):
     return self.title
pre_save.connect(slug_set, sender=brand)     

#model model
class model(models.Model):
    sno= models.AutoField(primary_key=True)
    title=models.CharField(max_length=100)
    Model_code=models.CharField(max_length=100, default="")
    image=models.ImageField(upload_to='images', default='')
    Chipset=models.CharField(max_length=200, default="")
    Cat=models.ManyToManyField(category, blank=True)
    chipset_description=models.CharField(max_length=400, null=True)
    Brand = models.ForeignKey(brand,on_delete=models.CASCADE, default="")
    slug=models.SlugField(default="", blank=True)
    Tags = TaggableManager(blank=True) 

    def brandname(self):
        return self.Brand__title
    def categories(self):
        return ",".join([str(p) for p in self.Cat.all()])
    def __str__(self):
     return self.title
    
@receiver(m2m_changed, sender=model.Tags.through)
def add_model_tags(sender, instance, action, pk_set, **kwargs):
    if action == 'post_add':
        tags = [instance.title,"firmware"]
        for tag in tags:
            if tag not in instance.Tags.names():
                instance.Tags.add(tag)

pre_save.connect(slug_set, sender=model)   

def get_default_superuser():
    return User.objects.filter(is_superuser=True).first()

#resource model
class resource(models.Model):
    uploaded_by=models.ForeignKey(User,blank=True, on_delete=models.SET_NULL, null=True)
    title=models.CharField(max_length=100)
    size=models.CharField( max_length=20, default="")
    desc=models.TextField(default="")
    file=models.FileField(default="", blank=True)
    url= models.URLField(max_length=200, blank=True)
    varient=models.CharField(max_length=100, default="")
    Brand = models.ForeignKey(brand,on_delete=models.CASCADE, default="")
    Model = models.ForeignKey(model,on_delete=models.CASCADE, default="")
    Categories = models.ForeignKey(category,on_delete=models.CASCADE, default="")
    update_at=models.DateField(auto_now=True)
    pro=models.BooleanField(default=False)
    verified=models.BooleanField(default=False)
    slug=models.SlugField(default="", unique=True, blank=True)
    Tags = TaggableManager(blank=True) 

    def save(self, *args, **kwargs):
        check=resource.objects.all()
        if check.count() == 0:
            newid=1
        else:
            getlast=check.last()
            getid=getlast.id
            print(getid)
            newid=int(getid)+1
        if not self.pk:
            self.pk=newid

        tags = [self.title, self.varient,"firmware"]
        for tag in tags:
            if tag not in self.Tags.names():
                self.Tags.add(tag)
        if self.verified and self.pk:
            username = self.uploaded_by
            user = User.objects.get(username=username)
            user_is_staff = user.is_staff
            if not user_is_staff:
                permission=credits_permissions.objects.first()  
                if permission and permission.upload_Resource:  
                  contributer=user_profile.objects.get(username=user)
                  contributer.credits += 1
                  contributer.save()           
                if contributer.referrer_code != "":
                    if permission and permission.referrad_credit_for_resource:
                        referral_user=user_profile.objects.get(referral_code=contributer.referrer_code)
                        referral_user.credits+=1
                        referral_user.save()
        super(resource, self).save(*args, **kwargs)
        
@receiver(m2m_changed, sender=resource.Tags.through)
def add_resource_tags(sender, instance, action, pk_set, **kwargs):
    if action == 'post_add':
        tags = [instance.title, instance.varient,"firmware"]
        for tag in tags:
            if tag not in instance.Tags.names():
                instance.Tags.add(tag)
pre_save.connect(slug_set, sender=resource)

#userprofile
class user_profile(models.Model):
    username=models.ForeignKey(User, on_delete=models.CASCADE)
    phoneNomber=models.CharField( max_length=14, blank=True)
    name=models.CharField(max_length=100, blank=True)
    address=models.CharField(max_length=500,blank=True)
    referral_code=models.CharField(max_length=10, default='', blank=True )
    referrer_code=models.CharField(max_length=10, default='', blank=True)
    credits=models.IntegerField(default=0)
    
    def __str__(self):
     return self.username.username
    
# ads managments  
class ads(models.Model):
    
     CHOICES = (
      ("localads", "local ads"),
      ("adsenseads", "adsense ads"),
      ("affliateads", "affliate ads"),
    )

     adschoice = models.CharField(max_length=15,choices=CHOICES)
     banner_image=models.ImageField(upload_to="ads", blank=True)
     url=models.URLField()
     Time=models.DateTimeField(default=now)
     Timestemp=models.CharField(max_length=3, help_text="in days")

     @property
     def value(self):
        if  self.adschoice=="localads":
            return self.url
        if self.adschoice=="adsenseads":
            return self.banner_image
        else:
            return self.Time  


class  socialLinks(models.Model):
    Facebook_URL=models.URLField(max_length=200, blank=True) 
    Instragram_URL=models.URLField(max_length=200, blank=True) 
    Twitter_URL=models.URLField(max_length=200, blank=True) 
    Youtube_URL=models.URLField(max_length=200, blank=True) 

def get_facebook_url():
        social_links = socialLinks.objects.first()
        return social_links.Facebook_URL 
 


class onsitedata(models.Model):
    Website_Title=models.CharField(max_length=100,blank=True)
    Website_URL=models.URLField(max_length=200, blank=True)
    Website_Logo=models.ImageField(upload_to="logo", blank=True)
    Meta_Description=models.CharField(max_length=300, blank=True)
    Meta_Keywords= models.CharField( max_length=500, blank=True)
    Contact_email=models.EmailField(max_length=50, blank=True)
    Mail_Password=models.CharField(max_length=100, blank=True)

class pages(models.Model):
    page = (
      ("about", "About"),
      ("contact", "Contact"),
      ("refund-policy", "Refund Policy"),
      ("return-policy", "Return Policy"),
      ("privacy-policy", "Privacy Policy"),
      ("cancellation-policy", "Cancellation Policy"),
      ("terms-of-services", "Terms Of Services"),
    )
    
    select_page = models.CharField(max_length=50,choices=page, default='')
    title=models.CharField(max_length=500, default="")
    description=models.TextField()    
    active=models.BooleanField(default=True)   

    def __str__(self):
        return self.title  

class custom_page(models.Model):
    set = (
      ("header", "header"),
      ("footer", "footer"),
    )
    location = models.CharField(max_length=15,choices=set, default='')
    title=models.CharField(max_length=500, default="")
    description=models.TextField()    
    active=models.BooleanField(default=False)  
    slug=models.SlugField(default="",  blank=True)

    def __str__(self):
        return self.title 
pre_save.connect(slug_set, sender=custom_page)



class notification(models.Model):
    message=models.CharField(max_length=300, blank=False)
    time_stemp=models.IntegerField(help_text="enter in days", default=0, blank=False ) 
    created_at = models.DateTimeField(default=timezone.now)

    def is_displayable(self):
        time_elapsed = timezone.now() - self.created_at
        display_duration = timezone.timedelta(days=self.time_stemp)
        return time_elapsed <= display_duration    

    def __str__(self):
        return self.message 

    

subscriptionApp/forms.py

from django import forms
from gsmApp.models import *
from blogApp.models import article
from django.contrib.admin.widgets import ForeignKeyRawIdWidget
from taggit.forms import TagField
from django_summernote.widgets import SummernoteWidget

# class ResourceForm(forms.ModelForm):
#     class Meta:
#         model = resource
#         fields = '__all__'
        # widgets = {
        #     'Brand': ModelSelect2Widget(
        #         model=brand,
        #         search_fields=['name__icontains'],
        #         new_item_label='Add new brand'
        #     ),
        # }
        # fields = ['title', 'size', 'desc','url','varient','Model','Categories','Tags']


    
from django import forms
from django.urls import reverse
from django.utils.safestring import mark_safe
from taggit.forms import TagField
from gsmApp.models import brand, model, category, resource
from django.contrib.admin.widgets import ForeignKeyRawIdWidget
from django.urls import reverse_lazy


# class RawIdWidget(forms.TextInput):
#     template_name = 'templates/subscriptionApp/raw_id_widget.html'

#     def __init__(self, model, *args, **kwargs):
#         self.model = model
#         super().__init__(*args, **kwargs)

#     def get_url(self):
#         return reverse('admin:%s_%s_add' % (
#             self.model._meta.app_label, self.model._meta.model_name
#         ))

#     def get_context(self, name, value, attrs):
#         context = super().get_context(name, value, attrs)
#         context['widget']['url'] = self.get_url()
#         return context


class BrandForm(forms.ModelForm):
    class Meta:
        model = brand
        fields = '__all__'


class ModelForm(forms.ModelForm):
    class Meta:
        model = model
        fields = '__all__'


class CategoryForm(forms.ModelForm):
    class Meta:
        model = category
        fields = '__all__'


class ResourceForm(forms.ModelForm):
   class Meta:
        model = resource
        fields = '__all__'
#         widgets = {
#             'Brand': ForeignKeyRawIdWidget(
#                 rel=brand._meta.get_field('id').remote_field,
#                 # admin_site=admin.site,
#                 attrs={
#                     'class': 'vForeignKeyRawIdAdminField',
#                     'data-popup-url': reverse_lazy('create-brand')
#                 }
#             ),
#             'Model': ForeignKeyRawIdWidget(
#                 rel=model._meta.get_field('id').remote_field,
#                 # admin_site=admin.site,
#                 attrs={'class': 'vForeignKeyRawIdAdminField'}
#             ),
#             'Categories': forms.CheckboxSelectMultiple(attrs={'class': 'list-unstyled'}),
#             'Tags': forms.TextInput(attrs={'class': 'form-control'}),
#         }

#    def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['Brand'].widget.can_add_related = True
# class Media:
#         js = ('js/resource_form.js',)

class blogPostForm(forms.ModelForm):
    desc = forms.CharField(widget=SummernoteWidget())
    
    class Meta:
        model=article
        fields=['title','desc','Model']

subscriptionApp/templates/contribution/addBlogPost.html
{% extends 'firmApp/basic.html'%}{% load static %}
{% block title %}about us {% endblock %}
{% block css %}<style>
    .mb-3{
        display: flex;
        justify-content: center;
        flex-direction: column;
    }
    .mb-3 input, .mb-3 select{
        height: 40px;
        width: 98%
    }
    .mb-3 input,.mb-3 textarea,.mb-3 select{
        border: 2px solid rgb(224, 224, 224);
        border-radius: 0.375rem;
        padding-left: 10px;        
    }
    .form-label{
        font-weight: bold;
    }

    /* Summernote CSS */
    .note-editor {
        max-width: 100%;
    }
    .note-editor .note-editing-area {
        min-height: 200px;
    }
    .note-editor .note-toolbar {
        background-color: #F8F9FA;
        border: none;
        border-bottom: 1px solid #E2E3E5;
    }
    .note-editor .note-statusbar {
        background-color: #F8F9FA;
        border: none;
        border-top: 1px solid #E2E3E5;
    }
    .note-editor .note-resizebar {
        background-color: #E2E3E5;
        border: none;
    }
    .note-editor .dropdown-menu {
        max-height: 200px;
        overflow-y: auto;
    }
</style>{% endblock %}
{% block body %}



   <div class="container mt-3 mb-3">

    <div class="row d-flex justify-content-center">
        <div class="col-md-8 col-9 ">
            <h2 align='center'>Blog Post</h2>
            <form method="post" , action=""> {% csrf_token %}

                <div class="mb-3">
                    <label for="title" class="form-label">Title:</label>
                    {{form.title}}
                </div>
                <div class="mb-3">
                    <label for="desc" class="form-label">Description:</label>
                    {{form.desc}}
                </div>
                <div class="mb-3">
                    <label for="Model" class="form-label">Model:</label>
                    {{form.Model}}
                </div>

                <div class="d-grid gap-2">
                <button type="submit" class="btn btn-success mt-2">Submit</button>
                </div>
              
            <!-- </div> -->
            </form>
        </div>
    </div>
</div>
{% endblock %}

subscriptionApp/templates/contribution/addBrand.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <!-- create_brand.html -->
<h1>Create Brand</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_brand_name">Brand Name</label>
        <input type="text" name="brand_name" id="id_brand_name" class="form-control" required>
    </div>
    <input type="submit" value="Create Brand">
</form>

</body>
</html>

subscriptionApp/templates/contribution/addCategory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" class="form-horizontal">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="id_title" class="col-sm-2 control-label">Title</label>
            <div class="col-sm-10">
              <input type="text" name="title" class="form-control" id="id_title" placeholder="Enter title">
            </div>
          </div>
          </form>
</body>
</html>

subscriptionApp/templates/contribution/addFile.html
{% extends 'firmApp/basic.html'%}{% load static %}
{% block title %}about us {% endblock %}
{% block css %}<style>
    .mb-3{
        display: flex;
        justify-content: center;
        flex-direction: column;
    }
    .mb-3 input, .mb-3 select{
        height: 40px;
        width: 100%
    }
    .mb-3 input,.mb-3 textarea,.mb-3 select{
        border: 2px solid rgb(224, 224, 224);
        border-radius: 0.375rem;
        padding-left: 10px;        
    }
    .form-label{
        font-weight: bold;
    }

  
</style>{% endblock %}
{% block body %}



   <div class="container mt-3 mb-3">

    <div class="row d-flex justify-content-center">
        <div class="col-md-8 col-9 ">
            <h2 align='center'>post a file</h2>
            <form method="post" enctype="multipart/form-data"> {% csrf_token %}
              
                <div class="mb-3">
                    <label for="title" class="form-label">Title:</label>
                    {{form.title}}
                </div>
                <div class="mb-3">
                  <label for="size" class="form-label">Size:</label>
                  {{form.size}}
              </div>
                <div class="mb-3">
                    <label for="desc" class="form-label">Description:</label>
                    {{form.desc}}
                </div>
                <div class="mb-3">
                    <label for="file" class="form-label">File:</label>
                    {{form.file}}
                </div>
                <div class="mb-3">
                  <label for="varient" class="form-label">Varient:</label>
                  {{form.varient}}
              </div>
              <div class="mb-3">
                <label for="Brand" class="form-label">Brand:</label>
                {{form.Brand}}
            </div>
              <div class="mb-3">
                <label for="model" class="form-label">Model:</label>
                {{form.Model}}
            </div>
            <div class="mb-3">
              <label for="Categories" class="form-label">Category:</label>
              {{form.Categories}}
          </div>
                

                <div class="d-grid gap-2">
                <button type="submit" class="btn btn-success mt-2">Submit</button>
                </div>
              
            
            </form>
        </div>
    </div>
</div>
{% endblock %}

subscriptionApp/templates/contribution/addModel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        
        <div class="form-group">
          <label for="id_title" class="col-sm-2 control-label">Title</label>
          <div class="col-sm-10">
            <input type="text" name="title" class="form-control" id="id_title" placeholder="Enter title">
          </div>
        </div>
        
        <div class="form-group">
          <label for="id_Model_code" class="col-sm-2 control-label">Model Code</label>
          <div class="col-sm-10">
            <input type="text" name="Model_code" class="form-control" id="id_Model_code" placeholder="Enter model code">
          </div>
        </div>
        
        <div class="form-group">
          <label for="id_Chipset" class="col-sm-2 control-label">Chipset</label>
          <div class="col-sm-10">
            <input type="text" name="Chipset" class="form-control" id="id_Chipset" placeholder="Enter chipset">
          </div>
        </div>
        
        <div class="form-group">
          <label for="id_chipset_description" class="col-sm-2 control-label">Chipset Description</label>
          <div class="col-sm-10">
            <input type="text" name="chipset_description" class="form-control" id="id_chipset_description" placeholder="Enter chipset description">
          </div>
        </div>
        
        <div class="form-group">
          <label for="id_Brand" class="col-sm-2 control-label">Brand</label>
          <div class="col-sm-10">
            <div class="input-group">
              <select name="Brand" class="form-control" id="id_Brand">
                {% for brand in brands %}
                  <option value="{{ brand.id }}">{{ brand.name }}</option>
                {% endfor %}
              </select>
              <div class="input-group-append">
                <a href="{% url 'create_brand' %}" class="btn btn-outline-secondary" target="_blank">
                  <i class="fa fa-plus"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
        
        <div class="form-group">
          <label for="id_Cat" class="col-sm-2 control-label">Category</label>
          <div class="col-sm-10">
            <div class="input-group">
              <select name="Cat" class="form-control" id="id_Cat" multiple>
                {% for category in categories %}
                  <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
              </select>
              <div class="input-group-append">
                <a href="{% url 'create_category' %}" class="btn btn-outline-secondary" target="_blank">
                  <i class="fa fa-plus"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
        
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
        
      </form>
      
</body>
</html>